builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.Version={{.Version}}
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    # ignore:
    #   - goos: windows
    #     goarch: arm64
    #   - goos: windows
    #     goarch: arm
checksum:
  name_template: checksums.txt
snapshot:
  name_template: "{{ .Tag }}-next"
release:
  prerelease: auto
changelog:
  sort: asc
